export const SKILLS_BY_INDUSTRY: Record<string, string[]> = {
  Technology: [
    "Software Engineering",
    "Full Stack Development",
    "Frontend Development",
    "Backend Development",
    "Mobile Development",
    "DevOps",
    "Cloud Architecture",
    "System Design",
    "Data Engineering",
    "Machine Learning",
    "AI/ML",
    "Data Science",
    "UI/UX Design",
    "Product Design",
    "Product Management",
    "Technical Writing",
    "Agile Methodology",
    "Scrum",
    "API Development",
    "Cybersecurity",
  ],
  Finance: [
    "Financial Analysis",
    "Investment Banking",
    "Portfolio Management",
    "Risk Management",
    "Financial Modeling",
    "Valuation",
    "Corporate Finance",
    "Accounting",
    "Quantitative Analysis",
    "Trading",
    "Compliance",
    "Audit",
    "Financial Planning",
    "Tax Strategy",
    "M&A",
    "Private Equity",
    "Venture Capital",
    "Excel Modeling",
    "SQL",
    "Bloomberg Terminal",
  ],
  Healthcare: [
    "Clinical Research",
    "Healthcare Management",
    "Medical Billing",
    "Patient Care",
    "Healthcare IT",
    "Electronic Health Records",
    "Regulatory Compliance",
    "HIPAA",
    "Medical Coding",
    "Public Health",
    "Epidemiology",
    "Healthcare Analytics",
    "Telemedicine",
    "Healthcare Operations",
    "Quality Assurance",
    "Patient Safety",
    "Pharmacy",
    "Medical Device",
    "Biotechnology",
    "Clinical Trials",
  ],
  Education: [
    "Curriculum Development",
    "Instructional Design",
    "Educational Technology",
    "Learning Management Systems",
    "Student Assessment",
    "Classroom Management",
    "Special Education",
    "ESL/ELL",
    "Educational Leadership",
    "Academic Advising",
    "Training & Development",
    "E-Learning",
    "Educational Research",
    "Student Affairs",
    "Higher Education",
    "K-12 Education",
    "Tutoring",
    "Pedagogy",
    "EdTech",
    "Educational Psychology",
  ],
  Marketing: [
    "Digital Marketing",
    "Content Marketing",
    "SEO/SEM",
    "Social Media Marketing",
    "Email Marketing",
    "Marketing Analytics",
    "Brand Strategy",
    "Copywriting",
    "Graphic Design",
    "Video Production",
    "Growth Marketing",
    "Performance Marketing",
    "Marketing Automation",
    "CRM",
    "Google Analytics",
    "A/B Testing",
    "Influencer Marketing",
    "PR",
    "Event Marketing",
    "Market Research",
  ],
  Other: [
    "Project Management",
    "Business Analysis",
    "Strategic Planning",
    "Operations Management",
    "Sales",
    "Business Development",
    "Customer Success",
    "Account Management",
    "Leadership",
    "Team Management",
    "Stakeholder Management",
    "Negotiation",
    "Data Analysis",
    "Problem Solving",
    "Communication",
    "Presentation Skills",
    "Process Improvement",
    "Change Management",
    "Consulting",
    "Research",
  ],
};

// All skills combined for autocomplete
export const ALL_SKILLS: string[] = Object.values(SKILLS_BY_INDUSTRY)
  .flat()
  .sort((a, b) => a.localeCompare(b));
